#!/bin/sh

mount -a

# added by huangqingjia for sysfs
mount -t sysfs /sys /sys
# ended add

tcwdog -t 1 /dev/watchdog &
/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp
/bin/mkdir -m 0777 -p /var/Wireless/RT2860AP
/bin/mkdir -m 0777 -p /var/tmp/wsc_upnp

/bin/mkdir -m 0777 -p /var/tmp/dropbear

#for the dirs of samba and ntfs-3g, zjj, 20111129
/bin/mkdir -m 0777 -p /var/3G
/bin/mkdir -m 0777 -p /var/usbdisk
/bin/mkdir -m 0777 -p /var/dev
/bin/mkdir -m 0777 -p /var/samba/lib
/bin/mkdir -m 0777 -p /var/samba/private
/bin/mkdir -m 0777 -p /var/samba/var/locks
cp -p /etc/passwd.bak /var/passwd

/bin/mkdir -m 0777 -p /var/easy-rsa
/bin/mkdir -m 0777 -p /var/easy-rsa/keys
/bin/mkdir -m 0777 -p /var/openvpn

/bin/mkdir -m 0777 -p /var/pptpd

#for https certificate
/bin/mkdir -m 0777 -p /var/https

echo 2560 > /proc/sys/vm/min_free_kbytes

cp /etc_conf/Wireless/RT2860AP/* /var/Wireless/RT2860AP/

#add by Zhao Mengqing, 2016-4-2
insmod /lib/modules/module_sel.ko
insmod /lib/modules/tcledctrl.ko
insmod /lib/modules/tccicmd.ko
insmod /lib/modules/wlan_ratelimit.ko
insmod /lib/modules/crypto_k.ko
insmod /lib/modules/fe_core.ko
insmod /lib/modules/qdma_lan.ko
insmod /lib/modules/eth.ko
insmod /lib/modules/eth_ephy.ko
#insmod /lib/modules/dying_gasp.ko

qdmamgr_lan set rxratelimit config Enable packet
qdmamgr_lan set rxratelimit value 0 60000
qdmamgr_lan set rxratelimit value 1 1000000

insmod /lib/modules/qdma_wan.ko physical_size=0x100000
qdmamgr_wan set rxratelimit config Enable packet
qdmamgr_wan set rxratelimit value 0 60000
qdmamgr_wan set rxratelimit value 1 1000000

ifconfig eth0 up

# ppp_mppe.ko
insmod /lib/modules/kmdir/kernel/crypto/arc4.ko
insmod /lib/modules/kmdir/kernel/crypto/ecb.ko
insmod /lib/modules/kmdir/kernel/drivers/net/ppp_mppe.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/pptp.ko
insmod /lib/modules/pptp.ko
#insmod /lib/modules/kmdir/kernel/drivers/net/ppp/pptp_fastpath.ko
ifconfig lo 127.0.0.1 netmask 255.0.0.0

echo 8192 > /proc/net/skbmgr_driver_max_skb
echo 4096 > /proc/net/skbmgr_limit
echo 4096 > /proc/net/skbmgr_4k_limit

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
#echo 5120 > /proc/sys/net/nf_conntrack_max
echo 4096 > /proc/sys/net/netfilter/nf_conntrack_expect_max
echo 6000 > /proc/sys/net/ipv6/neigh/default/gc_stale_time
echo 1 >/proc/sys/net/ipv6/conf/all/forwarding
echo 30 > /proc/sys/net/unix/max_dgram_qlen
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout
echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

#echo 8 >/proc/irq/22/smp_affinity
echo 3 > /proc/sys/vm/drop_caches
#end by Zhao Mengqing

mount -t usbfs usbfs /proc/bus/usb/

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_wait_scan.ko

# use mtk_xhci driver, original ohci-hcd can not be loaded, why ?
insmod /lib/modules/kmdir/kernel/drivers/usb/host/mtk_xhci/xhci-hcd.ko

#insmod /lib/modules/kmdir/kernel/drivers/usb/host/ehci-hcd.ko
#insmod /lib/modules/kmdir/kernel/drivers/usb/host/uhci-hcd.ko
#insmod /lib/modules/kmdir/kernel/drivers/usb/host/ohci-hcd.ko
if [ -e /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko ]; then
	insmod /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko;
fi

#netfilter modules load
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_proto_gre.ko
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_pptp.ko
# SFE accel
insmod /lib/modules/kmdir/kernel/net/nat/shortcut-fe/shortcut-fe.ko
insmod /lib/modules/kmdir/kernel/net/nat/shortcut-fe/shortcut-fe-ipv6.ko
#insmod /lib/modules/kmdir/kernel/net/nat/fast-classifier/fast-classifier.ko
insmod /lib/modules/kmdir/kernel/net/nat/shortcut-fe/shortcut-fe-cm.ko

insmod /lib/modules/ipt_STAT.ko
insmod /lib/modules/tp_domain.ko lan_domain=tplinkmodem.net

cp -p /etc/cloud/cloud_service.cfg /tmp/cloud_service.cfg

echo set q_update_token_interval 1400 >/proc/tc3162/wlan_ratelimit_config
echo ra0 rx 300000 >/proc/tc3162/wlan_ssid_ratelimit
echo ra0 tx 300000 >/proc/tc3162/wlan_ssid_ratelimit
echo ra1 rx 300000 >/proc/tc3162/wlan_ssid_ratelimit
echo ra1 tx 300000 >/proc/tc3162/wlan_ssid_ratelimit

# QDMA_LAN
echo 8 > /proc/irq/22/smp_affinity
# QDMA_WAN
echo 4 > /proc/irq/23/smp_affinity
# ra0, need to be confirmed
echo 3 > /proc/irq/24/smp_affinity
# wifi_ratelimit
echo 3 > /proc/irq/7/smp_affinity

insmod /lib/modules/pwm.ko
echo 1 > /proc/tc3162/pwm_start

cos &
telnetd &
